### ISSUE TITLE
Random blank line?

### ISSUE THREAD

**Issue by woook** [moka-guys/agilent_array_design_files#4]
https://github.com/moka-guys/agilent_array_design_files/blob/e43e0985af142d314e86e19c9bf9559643429492/turn_probes_off.py#L19

**Comment by aledj2** [comment]
no - they are deliberate blank lines.

**Comment by woook** [comment]
what's the logic behind them?

**Comment by aledj2** [comment]
I think it makes it easier to read, breaking ?up the file paths which must be specified into input xml files, input bedfiles and output files. This is described in the comments so the blank lines are not essential but personally think it makes it more readable, not sure ho it fits in with PEP8.

Aled
________________________________

**Comment by woook** [comment]
I'm happy with blank lines but would prefer that there is a consistent logic applied. How about adding a blank line between output xml & output bed (as you have for inputs)?
